CREATE database project;
show databases;
 use project;
 
CREATE TABLE PMS_DEPARTMENT_DETAILS(DEPARTMENT_ID INT(2)PRIMARY KEY,
DEPARTMENT_NAME VARCHAR(30)NOT NULL,
DEPARTMENT_LOCATION VARCHAR(30)NOT NULL,
DEPARTMENT_EXTENSION INT(3) NOT NULL);

CREATE TABLE PMS_MANAGER_DETAILS(Manager_ID INT(5) PRIMARY KEY,
Manager_Name VARCHAR(30) NOT NULL,
Job VARCHAR(30) NOT NULL,
Boss_Code INT(5),
Salary float(7,2) NOT NULL,
Commission INT(5),
DEPARTMENT_ID INT(2)); 

CREATE TABLE PMS_UNIT_DETAILS(UNIT_ID VARCHAR(2) PRIMARY KEY,
UNIT_NAME VARCHAR(30) NOT NULL,
PIECE_WEIGHT VARCHAR(15) NOT NULL,
TOTAL_PIECES int(3) NOT NULL,
UNIT_WEIGHT float(5,2) NOT NULL);

CREATE TABLE PMS_PRODUCT(PRODUCT_ID VARCHAR(5) PRIMARY KEY,
PRODUCT_NAME VARCHAR(30) NOT NULL,
DEPARTMENT_ID int(2));

CREATE TABLE PMS_MANUFACTURING(MANFATURE_ID VARCHAR(5) PRIMARY KEY,
PRODUCT_ID VARCHAR(5) NOT NULL,
UNIT_ID VARCHAR(5) NOT NULL,
QUANTITY int(7) NOT NULL,
AVAILABILITY VARCHAR(3) NOT NULL,
PRODUCT_MANFACTURE_DATE DATE NOT NULL,
PRODUCT_EXPIRY_DATE DATE NOT NULL);

CREATE TABLE PMS_PRODUCT_UNIT(PRODUCT_ID VARCHAR(5),
UNIT_ID VARCHAR(2));

INSERT INTO PMS_DEPARTMENT_DETAILS VALUES(10,'MIS','HYDERABAD_ZONE_1',121);
INSERT INTO PMS_DEPARTMENT_DETAILS VALUES(20,'GHEE SECTION','ONGOLE',122);
INSERT INTO PMS_DEPARTMENT_DETAILS VALUES(30,'PROCESSING SECTION','RAJAMUNDRY',123);
INSERT INTO PMS_DEPARTMENT_DETAILS VALUES(40,'BI_PRODUCTS SECTION','SECUNDERABAD',124);
INSERT INTO PMS_DEPARTMENT_DETAILS VALUES(50,'DISPATCH SECTION','HYDERABAD_ZONE_2',125);
INSERT INTO PMS_DEPARTMENT_DETAILS VALUES(60,'CUSTOMER CARE SECTION','HYDERABAD_ZONE_2',126);